### ISSUE TITLE
UTF-8 error

### ISSUE THREAD

**Issue by lbain** [vinibaggio/discover-unused-partials#15]
I tried to run this in my Rails app, but I got the error:

```
discover-unused-partials-0.3.1/lib/discover-unused-partials.rb:88:in `strip!': invalid byte sequence in UTF-8 (ArgumentError)
```

Any hints?

**Comment by gonchs** [comment]
+1

**Comment by gonchs** [comment]
Quick fix: add this at the beginning of discover-unused-partials.rb

if RUBY_VERSION =~ /1.9/
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

**Comment by vinibaggio** [comment]
Sorry for the long delay. I will take a look later today!

**Comment by harigopal** [comment]
I'm encountering an error that's probably related:

`.../gems/ruby-2.2.1/gems/discover-unused-partials-0.3.1/lib/discover-unused-partials.rb:90:in block (3 levels) in process_partials: invalid byte sequence in US-ASCII (ArgumentError)`

Got around it by doing:
```
$ export LANG=en_US.UTF-8
$ export LANGUAGE=en_US.UTF-8
$ export LC_ALL=en_US.UTF-8
$ discover-unused-partials
```

**Comment by tbcooney** [comment]
Was this ever resolved?

**Comment by RicardoTrindade** [comment]
way late to the party but this one worked for me 
`export RUBYOPT="-KU -E utf-8:utf-8" && discover-unused-partials`

**Comment by rvirani1** [comment]
None of these fixes are working for me

**Comment by RicardoTrindade** [comment]
@rvirani1 can you if you have any files other than .rb/.erb in your directories ? I was getting some errors with some docx and pdf that were sitting in one of the folders

**Comment by vinibaggio** [comment]
v0.3.5 was released with the fix for this issue.

**Comment by AlecRust** [comment]
I still get this error with 0.3.5:

```sh
/Users/alec/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:88:in `strip!': invalid byte sequence in UTF-8 (ArgumentError)
```

**Comment by GoudekettingRM** [comment]
Same.. 

Trace: 
```
	16: from /Users/robingoudeketting/.rbenv/versions/2.5.0/bin/discover-unused-partials:23:in `<main>'
	15: from /Users/robingoudeketting/.rbenv/versions/2.5.0/bin/discover-unused-partials:23:in `load'
	14: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/bin/discover-unused-partials:24:in `<top (required)>'
	13: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:6:in `find'
	12: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:6:in `chdir'
	11: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:6:in `block in find'
	10: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:63:in `used_partials'
	 9: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:63:in `loop'
	 8: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:64:in `block in used_partials'
	 7: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:85:in `process_partials'
	 6: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:85:in `each'
	 5: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:86:in `block in process_partials'
	 4: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:86:in `open'
	 3: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:87:in `block (2 levels) in process_partials'
	 2: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:87:in `each'
	 1: from /Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:88:in `block (3 levels) in process_partials'
/Users/robingoudeketting/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:88:in `strip!': invalid byte sequence in UTF-8 (ArgumentError)
```

**Comment by GoudekettingRM** [comment]
Seems like the release didn't go according to plan. Checked out the file and line 88 still shows `line.strip!`.
