### ISSUE TITLE
Undefined method `exists?` for File:Class (NoMethodError)

### ISSUE THREAD

**Issue by noloman** [vinibaggio/discover-unused-partials#30]
Hi,

I'm running `discover-unused-partials` on the current directory and I'm running into this:

```
/Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:122:in `block in check_extension_path': undefined method `exists?' for File:Class (NoMethodError)

      "#{file}#{EXT.find{ |e| File.exists? file + e }}"
                                  ^^^^^^^^
Did you mean?  exist?
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:122:in `each'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:122:in `find'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:122:in `check_extension_path'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:104:in `block (3 levels) in process_partials'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:87:in `each'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:87:in `block (2 levels) in process_partials'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:86:in `open'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:86:in `block in process_partials'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:85:in `each'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:85:in `process_partials'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:64:in `block in used_partials'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:63:in `loop'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:63:in `used_partials'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:6:in `block in find'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:6:in `chdir'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/lib/discover-unused-partials.rb:6:in `find'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/discover-unused-partials-0.3.5/bin/discover-unused-partials:24:in `<top (required)>'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/bin/discover-unused-partials:25:in `load'
	from /Users/myuser/.asdf/installs/ruby/3.2.2/bin/discover-unused-partials:25:in `<main>'
```

I'm using Ruby 3.2.2 and Rails 7.0.7

**Comment by vinibaggio** [comment]
This was fixed in the newest release: 0.3.6.
