### ISSUE TITLE
Having troubles with UTF-8?

### ISSUE THREAD

**Issue by killthekitten** [vinibaggio/discover-unused-partials#7]
Simply installed gem and runned `discover-unused-partials` in RAILS_ROOT.
Got this output:

```
/usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:34:in `block (3 levels) in used_partials': invalid byte sequence in UTF-8 (ArgumentError)
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:32:in `each'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:32:in `block (2 levels) in used_partials'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:31:in `open'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:31:in `block in used_partials'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:76:in `block (2 levels) in each_file'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:76:in `block (2 levels) in each_file'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:78:in `block in each_file'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:74:in `each'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:74:in `each_file'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:76:in `block in each_file'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:74:in `each'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:74:in `each_file'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:76:in `block in each_file'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:74:in `each'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:74:in `each_file'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:30:in `used_partials'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/lib/discover-unused-partials.rb:7:in `find_in'
     from /usr/local/Cellar/ruby/1.9.3-p125/lib/ruby/gems/1.9.1/gems/discover-unused-partials-0.1.0/bin/discover-unused-partials:18:in `<top (required)>'
     from /usr/local/Cellar/ruby/1.9.3-p125/bin/discover-unused-partials:19:in `load'
     from /usr/local/Cellar/ruby/1.9.3-p125/bin/discover-unused-partials:19:in `<main>'
```

**Comment by elalemanyo** [comment]
I am getting also some problems now with ruby 2.6

```
❯ discover-unused-partials
Traceback (most recent call last):
  17: from ~/.rvm/gems/ruby-2.6.5@rails/bin/ruby_executable_hooks:24:in `<main>'
  16: from ~/.rvm/gems/ruby-2.6.5@rails/bin/ruby_executable_hooks:24:in `eval'
  15: from ~/.rvm/gems/ruby-2.6.5@rails/bin/discover-unused-partials:23:in `<main>'
  14: from ~/.rvm/gems/ruby-2.6.5@rails/bin/discover-unused-partials:23:in `load'
  13: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/bin/discover-unused-partials:24:in `<top (required)>'
  12: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:6:in `find'
  11: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:6:in `chdir'
  10: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:6:in `block in find'
   9: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:63:in `used_partials'
   8: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:63:in `loop'
   7: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:64:in `block in used_partials'
   6: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:85:in `process_partials'
   5: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:85:in `each'
   4: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:86:in `block in process_partials'
   3: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:86:in `open'
   2: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:87:in `block (2 levels) in process_partials'
   1: from ~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:87:in `each'
~/.rvm/gems/ruby-2.6.5@rails/gems/discover-unused-partials-0.3.4/lib/discover-unused-partials.rb:89:in `block (3 levels) in process_partials': invalid byte sequence in UTF-8 (ArgumentError)
```
